# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DerogationPlugin
                                 A QGIS plugin
 gestion derogatio
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-23
        copyright            : (C) 2025 by imane
        email                : khoussi.imane@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
# -*- coding: utf-8 -*-
def classFactory(iface):
    from .gestion_derogations import GestionDerogationsPlugin
    return GestionDerogationsPlugin(iface)